// Initial seed data for the `PracticeArea` table.
// Used by `/api/practice-areas` GET to populate the table the first time it's
// queried with an empty result set. After the table has rows, this file is
// effectively reference data — keep it in sync if a new practice area should
// also be a default on fresh DBs.

export interface PracticeAreaSeed {
  title: string;
  slug: string;
  description: string;
  features: string[];
  image: string;
  banner: string;
  color: string;
  order: number;
}

export const practiceAreasSeedData: PracticeAreaSeed[] = [
  {
    title: "Personal Injury",
    slug: "personal-injury",
    description: "Our personal injury attorneys are dedicated to helping victims of negligence recover the compensation they deserve. We handle all types of personal injury cases with skill and compassion.",
    features: [
      "Slip and fall accidents",
      "Wrongful death claims",
      "Catastrophic injuries",
      "Brain and spinal cord injuries",
      "Burn injuries",
    ],
    image: "/photos/personal-injury.jpg",
    banner: "/photos/banner-personal-injury-1024x128.png",
    color: "blue",
    order: 1,
  },
  {
    title: "Auto Accidents",
    slug: "auto-accidents",
    description: "If you have been injured in a motor vehicle accident, our experienced attorneys can help you understand your legal options and develop a strategy for maximizing compensation.",
    features: [
      "Car accidents",
      "Motorcycle accidents",
      "Truck accidents",
      "Bicycle accidents",
      "Pedestrian accidents",
    ],
    image: "/photos/auto-accidents.jpg",
    banner: "/photos/banner-auto-1024x128.png",
    color: "red",
    order: 2,
  },
  {
    title: "Medical Malpractice",
    slug: "medical-malpractice",
    description: "Even well-meaning doctors make mistakes that can have a devastating effect on a patient's health. If you or someone you love has been a victim of medical malpractice, contact us today.",
    features: [
      "Surgical errors",
      "Misdiagnosis/delayed diagnosis",
      "Medication errors",
      "Birth injuries",
      "Hospital negligence",
    ],
    image: "/photos/medical.jpg",
    banner: "/photos/banner-medical-1024x128.png",
    color: "green",
    order: 3,
  },
  {
    title: "Premises Liability",
    slug: "premises-liability",
    description: "Property owners have an obligation to keep their premises safe. If they fail to do so, they may be liable for the damages, losses and injuries they've caused.",
    features: [
      "Slip and fall accidents",
      "Trip and fall accidents",
      "Inadequate security",
      "Swimming pool accidents",
      "Construction site accidents",
    ],
    image: "/photos/premises.jpg",
    banner: "/photos/banner-premises-1024x128.png",
    color: "purple",
    order: 4,
  },
  {
    title: "Workers' Compensation",
    slug: "workers-compensation",
    description: "If you've been injured on the job, you may be entitled to workers' compensation benefits. Our experienced attorneys can help you navigate the complex claims process.",
    features: [
      "Workplace injuries",
      "Occupational diseases",
      "Repetitive stress injuries",
      "Construction accidents",
      "Benefits appeals",
    ],
    image: "/photos/workers-comp.jpg",
    banner: "/photos/banner-workers-1024x128.png",
    color: "blue",
    order: 5,
  },
  {
    title: "Product Liability",
    slug: "defective-products",
    description: "When defective products cause injuries, manufacturers and distributors can be held responsible. We help victims of dangerous and defective products seek justice.",
    features: [
      "Defective automobiles",
      "Dangerous pharmaceuticals",
      "Defective medical devices",
      "Faulty consumer products",
      "Industrial equipment failures",
    ],
    image: "/photos/products.jpg",
    banner: "/photos/banner-products-1024x128.png",
    color: "red",
    order: 6,
  },
  {
    title: "Motorcycle Accidents",
    slug: "motorcycle-accidents",
    description: "Motorcycle accidents often result in serious injuries due to the lack of protection. Our attorneys understand the unique challenges motorcyclists face and fight for fair compensation.",
    features: [
      "Lane splitting accidents",
      "Intersection collisions",
      "Road hazard accidents",
      "Defective motorcycle parts",
      "Insurance claim disputes",
    ],
    image: "/photos/motorcycle.jpg",
    banner: "/photos/banner-motorcycle-1024x128.png",
    color: "green",
    order: 7,
  },
  {
    title: "Truck Accidents",
    slug: "truck-accidents",
    description: "Commercial truck accidents can cause devastating injuries and complex legal issues. Our experienced attorneys know how to handle these challenging cases.",
    features: [
      "18-wheeler accidents",
      "Delivery truck accidents",
      "Driver fatigue cases",
      "Improper loading accidents",
      "Commercial vehicle violations",
    ],
    image: "/photos/truck-accident.jpg",
    banner: "/photos/banner-truck-1024x128.png",
    color: "purple",
    order: 8,
  },
  {
    title: "Family Law",
    slug: "family-law",
    description: "Our family law attorneys provide compassionate representation during difficult times, helping families navigate complex legal matters with care and understanding.",
    features: [
      "Divorce proceedings",
      "Child custody disputes",
      "Child support matters",
      "Alimony/spousal support",
      "Adoption services",
    ],
    image: "/photos/general.jpg",
    banner: "/photos/banner-family-1024x128.png",
    color: "blue",
    order: 9,
  },
  {
    title: "Criminal Defense",
    slug: "criminal-defense",
    description: "If you're facing criminal charges, you need experienced legal representation. Our criminal defense attorneys protect your rights and fight for the best possible outcome.",
    features: [
      "DUI/DWI defense",
      "Drug crime defense",
      "Assault charges",
      "Theft and fraud charges",
      "Traffic violations",
    ],
    image: "/photos/criminal.jpg",
    banner: "/photos/banner-court-1024x128.png",
    color: "red",
    order: 10,
  },
  {
    title: "Social Security Disability",
    slug: "social-security-disability",
    description: "When disability prevents you from working, Social Security benefits can provide crucial financial support. We help clients navigate the complex application and appeals process.",
    features: [
      "Initial applications",
      "Appeals and hearings",
      "Disability determinations",
      "Benefits calculations",
      "Ongoing representation",
    ],
    image: "/photos/social-security.jpg",
    banner: "/photos/banner-social-1024x128.png",
    color: "green",
    order: 11,
  },
  {
    title: "General Legal Matters",
    slug: "general-legal-matters",
    description: "Our experienced team handles a wide range of legal matters, including real estate, landlord-tenant disputes, wills, estates, and probate, providing trusted guidance for your general legal needs.",
    features: [
      "Real Estate",
      "Landlord-Tenant Disputes and Litigation",
      "Wills",
      "Estates and Probate",
    ],
    image: "/photos/general.jpg",
    banner: "/photos/banner-court-1024x128.png",
    color: "blue",
    order: 12,
  },
  {
    title: "Limited Tort Lawyer",
    slug: "limited-tort-lawyer",
    description: "We help limited tort clients fight for fair compensation and prove their injuries meet the serious injury threshold.",
    features: [
      "Limited tort insurance exceptions",
      "Full tort qualification",
      "Insurance coverage review",
      "Serious injury litigation",
    ],
    image: "/photos/auto-accidents.jpg",
    banner: "/photos/banner-auto-1024x128.png",
    color: "red",
    order: 13,
  },
  {
    title: "Uber Lawyer",
    slug: "uber-lawyer",
    description: "Injured in an Uber or Lyft? We handle rideshare accident claims and insurance issues for drivers and passengers.",
    features: [
      "Uber/Lyft accident claims",
      "Insurance coverage gaps",
      "Passenger and driver representation",
      "Settlement negotiation",
    ],
    image: "/photos/auto-accidents.jpg",
    banner: "/photos/banner-auto-1024x128.png",
    color: "green",
    order: 14,
  },
  {
    title: "Taxi Lawyer",
    slug: "taxi-lawyer",
    description: "We represent clients injured in taxi accidents, guiding you through claims, insurance, and legal proceedings.",
    features: [
      "Taxi accident claims",
      "Insurance and legal system navigation",
      "Medical bill assistance",
      "Settlement and trial representation",
    ],
    image: "/photos/auto-accidents.jpg",
    banner: "/photos/banner-auto-1024x128.png",
    color: "purple",
    order: 15,
  },
  {
    title: "Septa Bus Accident Lawyer",
    slug: "septa-bus-accident-lawyer",
    description: "We help victims of SEPTA bus, trolley, and train accidents recover compensation for injuries and losses.",
    features: [
      "SEPTA bus, trolley, and train accidents",
      "Pedestrian and passenger injury claims",
      "Insurance and legal claims",
      "Expert investigation and evidence gathering",
    ],
    image: "/photos/auto-accidents.jpg",
    banner: "/photos/banner-auto-1024x128.png",
    color: "blue",
    order: 16,
  },
];
